name = "bendy-fs-server"
main = "build/worker.mjs"
compatibility_date = "2025-07-10"
account_id = "8fb5030dfc34621678a37a8abc90c7c2"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BENDY_FS_CONFIGS"
id = "64df8d6d63514c54b4d296edc0464853"

[vars]
# Set via `wrangler secret put`
# ADMIN_GITHUB_USERNAMES
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# GITHUB_REDIRECT_URI
# JWT_SECRET

[[d1_databases]]
binding = "BENDY_FS_DB"
database_name = "bendy-fs-db"
database_id = "554f2c34-4fdb-4ac9-bf3b-6081bd67a853"

[observability]
enabled = true
head_sampling_rate = 1

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = false

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
