name = "bendy-fs-server"
main = "build/worker.mjs"
compatibility_date = "2025-07-10"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BENDY_FS_CONFIGS"
id = "d633d4280dca44d3a03eb93728039bd2"
preview_id = "d633d4280dca44d3a03eb93728039bd2"

[vars]
# Set via `wrangler secret put`
# ADMIN_GITHUB_USERNAMES
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# GITHUB_REDIRECT_URI
# JWT_SECRET

[[d1_databases]]
binding = "BENDY_FS_DB"
database_name = "bendy-fs-db"
database_id = "be1939fd-eda9-4d7a-8434-e02176742152"

[observability]
enabled = true
head_sampling_rate = 1

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = false

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
